import os
from datetime import datetime
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession
from sqlalchemy.orm import declarative_base, sessionmaker
from sqlalchemy import Column, String, DateTime, ForeignKey, Text

# 1. Setup SQLite Async Engine
DATABASE_URL = "sqlite+aiosqlite:///./therapy_chats.db"
engine = create_async_engine(DATABASE_URL, echo=False)
SessionLocal = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)
Base = declarative_base()

# 2. Define the Database Tables
class ChatSession(Base):
    __tablename__ = "chat_sessions"
    
    session_id = Column(String, primary_key=True, index=True) # UUID generated by App
    user_email = Column(String, index=True, nullable=False)   # From the JWT
    title = Column(String, default="New Conversation")        
    created_at = Column(DateTime, default=datetime.utcnow)

class ChatMessage(Base):
    __tablename__ = "chat_messages"
    
    message_id = Column(String, primary_key=True, index=True) 
    session_id = Column(String, ForeignKey("chat_sessions.session_id"), nullable=False)
    role = Column(String, nullable=False)                     # "user" or "psychologist"
    content = Column(Text, nullable=False)                    
    detected_emotion = Column(String, nullable=True)          
    timestamp = Column(DateTime, default=datetime.utcnow)

# 3. Database Initialization Function
async def init_db():
    async with engine.begin() as conn:
        # This creates the tables if they don't exist yet
        await conn.run_sync(Base.metadata.create_all)

# 4. Database Session Generator for FastAPI
async def get_db():
    async with SessionLocal() as session:
        yield session